---
- name: Deploy an application to Fedora IoT
  hosts: fedora-iot
  vars:
    systemd_units_dir: "/etc/systemd/system/"
    service_name: "redis"
    container_image: "docker.io/redis"
    container_tag: "latest"
    container_port_mapping: "6379:6379"
    container_healthcheck_cmd: "/usr/local/bin/redis-cli info"
    container_healthcheck_interval: "30s"
    container_healthcheck_retries: 5
  tasks:
    - name: pull down container image
      containers.podman.podman_image:
        name: "{{ container_image }}"
        tag: "{{ container_tag }}"

    - name: template the systemd service unit file
      ansible.builtin.template:
        src: "templates/systemd_unit.j2"
        dest: "{{ systemd_units_dir }}/afit-{{ service_name }}.service"

    - name: template the systemd health check timer unit file
      ansible.builtin.template:
        src: "templates/systemd_timer.j2"
        dest: "{{ systemd_units_dir }}/afit-{{ service_name }}-healthcheck.timer"

    - name: template the systemd health check service unit file
      ansible.builtin.template:
        src: "templates/systemd_timer.j2"
        dest: "{{ systemd_units_dir }}/afit-{{ service_name }}-healthcheck.service"

    - name: deamon reload systemd and start our service
      ansible.builtin.systemd:
        name: "afit-{{service_name}}"
        state: started
        enabled: yes
        daemon_reload: yes
