---
# This playbook is meant to be an all-in-one
- name: Install the role
  hosts: localhost
  tasks:
    - name: install maxamillion.fedora_iot
      shell: ansible-galaxy install git+https://github.com/maxamillion/ansible-role-fedora-iot.git
      register: galaxy_install_out
      changed_when: '"installed successfully" in galaxy_install_out.stdout'
      failed_when: '"ERROR!" in galaxy_install_out.stdout'

- name: Run the ostree update
  hosts: localhost
  roles:
    - roles: maxamillion.fedora_iot
      vars:
        ostree_remote_name: rhel-for-edge-demo
        ostree_remote_url: 192.168.122.15:8000/
        ostree_content_url: 192.168.122.15:8000/repo
        ostree_gpg_verify: "false"
        ostree_upgrade: true
